In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("iris.csv")

In [3]:
dataset.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [4]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
dataset.shape

(150, 6)

In [6]:
X = dataset.iloc[:,:4].values
X

array([[  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   3. ,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       [  4. ,   4.6,   3.1,   1.5],
       [  5. ,   5. ,   3.6,   1.4],
       [  6. ,   5.4,   3.9,   1.7],
       [  7. ,   4.6,   3.4,   1.4],
       [  8. ,   5. ,   3.4,   1.5],
       [  9. ,   4.4,   2.9,   1.4],
       [ 10. ,   4.9,   3.1,   1.5],
       [ 11. ,   5.4,   3.7,   1.5],
       [ 12. ,   4.8,   3.4,   1.6],
       [ 13. ,   4.8,   3. ,   1.4],
       [ 14. ,   4.3,   3. ,   1.1],
       [ 15. ,   5.8,   4. ,   1.2],
       [ 16. ,   5.7,   4.4,   1.5],
       [ 17. ,   5.4,   3.9,   1.3],
       [ 18. ,   5.1,   3.5,   1.4],
       [ 19. ,   5.7,   3.8,   1.7],
       [ 20. ,   5.1,   3.8,   1.5],
       [ 21. ,   5.4,   3.4,   1.7],
       [ 22. ,   5.1,   3.7,   1.5],
       [ 23. ,   4.6,   3.6,   1. ],
       [ 24. ,   5.1,   3.3,   1.7],
       [ 25. ,   4.8,   3.4,   1.9],
       [ 26. ,   5. ,   3. ,   1.6],
       [ 27. ,   5. ,   3.4,   1.6],
 

In [7]:
y = dataset['Species'].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 0.53783972, -0.90029619, -1.25492481, -0.42967768],
       [ 0.95274465,  0.74015673, -0.11581   ,  0.9729698 ],
       [ 0.63004082,  1.44320798, -0.11581   ,  1.1973934 ],
       [ 0.88359383, -0.19724493, -1.25492481,  0.69244031],
       [-0.36112096, -0.78312098, -0.79927889,  0.07527541],
       [ 1.22934794,  0.62298153, -0.57145593,  1.0290757 ],
       [-1.4675341 , -1.25182181,  0.79548184, -1.21516027],
       [-1.05262917, -1.36899702,  0.33983592, -1.21516027],
       [-0.24586959, -0.31442014, -0.34363297, -0.09304228],
       [ 0.65309109,  0.50580632, -0.34363297,  1.0290757 ],
       [ 1.39069985,  2.14625924, -0.11581   ,  1.3096052 ],
       [-0.84517671, -1.72052264, -0.11581   , -1.38347797],
       [ 0.49173917, -0.19724493, -0.34363297,  0.24359311],
       [-1.0295789 , -1.25182181,  0.11201296, -1.21516027],
       [-1.09872972, -0.78312098,  1.0233048 , -1.27126617],
       [ 0.74529219,  1.6775584 , -0.34363297,  1.421817  ],
       [ 0.37648781,  0.

In [10]:
X_test

array([[ 0.12293479, -0.43159535, -1.48274777,  0.01916952],
       [ 0.86054356,  1.09168236, -0.11581   ,  0.9729698 ],
       [-0.38417123,  0.85733194, -0.34363297,  0.46801671],
       [-1.07567944, -0.78312098,  0.79548184, -1.32737207],
       [-1.16788054, -1.25182181,  0.79548184, -1.04684257],
       [ 1.16019712,  1.56038319,  0.33983592,  1.2534993 ],
       [-1.67498656, -1.36899702,  0.33983592, -1.38347797],
       [ 1.36764958,  0.2714559 , -1.02710185,  1.0290757 ],
       [-1.72108711, -0.90029619,  1.0233048 , -1.32737207],
       [ 0.60699054, -0.08006973, -0.79927889,  0.74854621],
       [-0.68382479, -1.25182181, -0.11581   , -1.32737207],
       [ 1.69035341,  0.38863111,  0.79548184,  0.9168639 ],
       [-0.45332205, -0.19724493, -0.57145593,  0.41191081],
       [-0.70687506, -0.90029619,  1.70677368, -1.04684257],
       [ 0.42258835, -1.01747139, -1.71057073, -0.26135998],
       [ 1.5290015 ,  1.20885757,  0.11201296,  0.74854621],
       [ 0.72224191, -1.

In [11]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [12]:
y_pred = classifier.predict(X_test) 
y_pred

array(['Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor'], dtype='<U15')

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  8]], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
Accuracy :  1.0

Accuracy :  0.9333333333333333


In [15]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0   Iris-versicolor  Iris-versicolor
1    Iris-virginica   Iris-virginica
2   Iris-versicolor  Iris-versicolor
3       Iris-setosa      Iris-setosa
4       Iris-setosa      Iris-setosa
5    Iris-virginica   Iris-virginica
6       Iris-setosa      Iris-setosa
7    Iris-virginica   Iris-virginica
8       Iris-setosa      Iris-setosa
9    Iris-virginica  Iris-versicolor
10      Iris-setosa      Iris-setosa
11   Iris-virginica   Iris-virginica
12  Iris-versicolor  Iris-versicolor
13      Iris-setosa      Iris-setosa
14  Iris-versicolor  Iris-versicolor
15   Iris-virginica   Iris-virginica
16   Iris-virginica  Iris-versicolor
17   Iris-virginica   Iris-virginica
18   Iris-virginica   Iris-virginica
19      Iris-setosa      Iris-setosa
20      Iris-setosa      Iris-setosa
21  Iris-versicolor  Iris-versicolor
22  Iris-versicolor  Iris-versicolor
23      Iris-setosa      Iris-setosa
24      Iris-setosa      Iris-setosa
25  Iris-versicolor  Iris-versicolor
26  Iris-versicolor  Iris-versicolor
27  Iris-versicolor  Iris-versicolor
28   Iris-virginica   Iris-virginica
29  Iris-versicolor  Iris-versicolor

In [16]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print metrics
print("Confusion Matrix:\n", cm)
print(f"Accuracy: {accuracy:.2f}")
print(f"Error Rate: {error_rate:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

Confusion Matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
Accuracy: 0.93
Error Rate: 0.07
Precision: 0.94
Recall: 0.93
